### ISSUE TITLE
Multiple 'Also published on Medium' links are displayed at top of post

### ISSUE THREAD

**Issue by troutcolor** [Medium/medium-wordpress-plugin#29] opened 2015-10-10 14:58 UTC
This can be seen: http://johnjohnston.info/blog/wordpress-to-medium/

The link is also at the bottom of the post where I would expect it.

I had to change all the short echo tags to the older style because I am running on php 5.3 so it might be my problem?

**Comment by majelbstoat** [comment] 2015-10-10 23:28
Hey @troutcolor, short tags will be fixed with #30. Not sure what is causing the multiple additional links. Perhaps the_content() is being called on things that are not a post? I'm going to look into that, thanks.

**Comment by majelbstoat** [comment] 2015-10-10 23:29
Do you use a custom theme, or one that I can get from the theme database? Do you have other plugins running? Did you make multiple revisions of the post before publishing, or re-publishing?

**Comment by majelbstoat** [comment] 2015-10-10 23:43
Ok, I pushed a change, which may fix it. Can you take the latest version and try again?

**Comment by troutcolor** [comment] 2015-10-11 09:53
Thanks @majelbstoat 
The short tags if fixed for me.

I am using a child theme of  SemPress
http://notizblog.org/projects/sempress/
https://wordpress.org/themes/sempress/

I did make several changes to the post before publishing. 
I've got **Cross-post as: None** set as default, and edited the post, saving a draft a few times.
I've added the new plugin. The multiple links are still on the post and on a new one:
http://johnjohnston.info/blog/this-medium-is-not-a-message/

I've got about 25 plugins running, can send a list, but it might be easier for me to test on a clean blog with sempress. I did this quickly and did not see the problem.

I also set my main blog back to the sempress theme, but still saw the problem. Which points to a plugin I guess. I'll try toggling them off one at a time and see.

**Comment by troutcolor** [comment] 2015-10-11 10:29
I toggled all of my plugins off and the problem seems to be when the medium plugin and **Jetpack** is activated.
I went through all of the jetpack modules I have active and toggled them off.
If I turn of the Publicize and Sharing Modules the multiple links go away. 
If I deactivate the Publicize module there is only one problematic link at the top of the single post view. Deactivating Sharing leaves all 4 problematic links.

I had set up another blog with no plugins  and did not see the problem.
Added the jetpack plugin and the publicize and Sharing modules. The problem links are added to the top of the post:
http://johnjohnston.info/wp2/index.php/2015/10/11/testing-post-to-medium/
Although only three at this post. (The medium post produced has been deleted).

I hope this is useful. apologies for the long posts here.

**Comment by majelbstoat** [comment] 2015-10-11 15:41
This is great, thanks.

**Comment by TheDavidJohnson** [comment] 2015-10-12 19:47
I'm just jumping in to let you know that I also experienced multiple links at the top of this post:
http://thedavidjohnson.com/2015/10/09/rebranding-epiphany/

Interestingly enough, I didn't notice the extra links at the top the day I posted it. I could've just been really, really blind and not paying attention (I doubt this), or perhaps something else changed since then.

I've not gone through the troubleshooting steps that @troutcolor did, but I can say that I do have Jetpack activated as well as the Medium plugin.

Also, if it helps to know this, I installed the plugin by downloading the zip rather than using Git. I'm going to update here shortly and see if the latest changes help. 

Thanks!

**Comment by TheDavidJohnson** [comment] 2015-10-12 20:27
FYI: I just updated to the latest version (including #30) and I still see the 4 extra links at the top. Will be more than happy to supply any troubleshooting info or cooperate however I can. Thanks!

**Comment by majelbstoat** [comment] 2015-10-14 16:49
Just to let you know, I'm still looking into this.

**Comment by majelbstoat** [comment] 2015-10-14 17:06
Ok, thanks to your information, I can now reproduce the problem locally. Working towards understanding why this is happening.

**Comment by majelbstoat** [comment] 2015-10-14 17:47
Should be fixed, please check out the latest version and let me know.

**Closed** 2015-10-14 17:46 UTC

**Comment by troutcolor** [comment] 2015-10-14 18:14
Yep both posts that showed the problem 
http://johnjohnston.info/blog/wordpress-to-medium/
and
http://johnjohnston.info/blog/this-medium-is-not-a-message/
don't show the extra text any more.
Many thanks
