### ISSUE TITLE
Issue when cross-posting

### ISSUE THREAD

**Issue by dkornyukhov** [Medium/medium-wordpress-plugin#35] opened 2015-10-17 20:58 UTC
Hey guys!
I'm using your plugin on my website: https://theopenmic.co and I'm having the following issue: Medium Error: Failure: Bad nested paragraphs: [ LI ] (-1)
I see this issue in the backend when viewing this post: https://theopenmic.co/how-to-add-tweets-to-your-stories/
Any ideas what might be causing the problem?

**Comment by majelbstoat** [comment] 2015-10-20 15:29
Thanks for the report @dkornyukhov. Can you paste here a small snippet of post HTML that triggers the error?

We'll take a look into this, cc: @kylehg.

**Comment by kylehg** [comment] 2015-10-20 20:51
@dkornyukhov I tested using the HTML on that page and it looks like the issue is your images inside the numbered list—we don't support images in our lists, only as free-standing paragraphs. 

(The API shouldn't be returning an error, though, so I'll investigate and fix that separately.)

**Comment by huckphin** [comment] 2016-02-05 04:10
@dkornyukhov Thank you for reporting the issue. This has been fixed on our backend. Thank you for using the API, and reporting the issue.

**Closed by huckphin** 2016-02-05 04:10 UTC
Labels: bug
