### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by 8BrickDMG** [Medium/medium-wordpress-plugin#36] opened 2015-10-19 13:38 UTC
Hi,

I recently installed the plugin into our Wordpress environment and I noticed that adding in the Medium token into the users profile page, causes an error 500 when saving. This can only be triggered when saving something in that field. Any other profile settings save fine.

Any ideas on how to resolve this? I've gone and added the token directly to the database to work around this.

Thanks!
Jason.

**Comment by fjarrett** [comment] 2015-10-19 14:26
Hi Jason, the more details you can provide about your environment, the better. This will help others reproduce the issue.

* WordPress version
* PHP version
* OS
* List of active plugins
* Theme name

**Comment by majelbstoat** [comment] 2015-10-20 15:32
Also, @8BrickDMG, can you include the (anonymised) error log line?

**Comment by 8BrickDMG** [comment] 2015-10-22 15:59
Hi @fjarrett and @majelbstoat. Here are the following details of the environment.

WordPress version = 4.3.1
PHP version = PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28)
OS = Ubuntu Server 15.04

List of active plugins =
AddThis Sharing Buttons v5.1.2
Contact Form 7 v4.3
Countdown Pro Wpdevart v10.0
Google XML Sitemaps v4.0.8
MailChimp for WordPress Lite v2.3.16
MailChimp Forms by MailMunch v2.1.2
Medium v1.0
OptionTree v2.5.5
Rotating Tweets (Twitter widget & shortcode) v1.7.18
WordPress Importer v0.6.1
WP Robots Txt v1.1
WP-SpamShield v1.9.6.3

Theme name = Awesome App Child (This has been modified slightly).

I do get this error log when I turn the debug setting on (if this isn't what you asked for, please help direct me to where I should be looking for the logs as I'm still learning Wordpress):

Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use
__construct()
instead. in /home/upteam/unleashingpotential.org.uk/wp-includes/functions.php on line 3457

Notice: A session had already been started - ignoring session_start() in /home/upteam/unleashingpotential.org.uk/wp-content/plugins/medium/lib/medium-admin.php on line 20

**Comment by wjmoner** [comment] 2015-10-28 18:10
I'm also receiving the same 500 Server Error when attempting to apply the integration key to a publication. Theme: Twenty-Fifteen default, no changes, no plugins other than Akismet. When I press reload after the 500 Error, I get a message in the browser stating "Invalid User ID."

**Comment by majelbstoat** [comment] 2015-10-28 20:16
Hey @wjmoner, that's very strange. Can you email the token you used to developers@medium.com for the attention of Jamie, and I can try and reproduce. (Does it happen for all tokens, if you generate another one for yourself from the settings page?)

Thanks for the info too, @8BrickDMG.

**Comment by Chrisjgreenough** [comment] 2015-11-05 05:49
We have a very similar environment and we are receiving the same error. There is no effect when creating new tokens. I've installed the plugin via Wordpress and via the zip file on GitHub separately just incase. Is it possible to also email you our token?

**Comment by majelbstoat** [comment] 2015-11-05 15:52
Yep, please do.

**Comment by majelbstoat** [comment] 2015-11-06 03:44
Ok, I've tested both the supplied tokens, and they are working as expected, which points to some kind of failure in the WP plugin itself.

You can try this yourself with curl on the command line:

```
curl -H 'Authorization: Bearer YOUR_ACCESS_TOKEN' https://api.medium.com/v1/me
```

Will do my best to dig in to the root cause, but without error messages, or a line number it's pretty hard.

**Comment by majelbstoat** [comment] 2015-11-06 05:34
Hey @wjmoner, @Chrisjgreenough, @8BrickDMG, 

Can you paste a screenshot of the exact errors you see in the browser? I've done extensive testing with large combinations of plugins without reproducing, so I think it must be something to do with server configuration. It might be to do with the version of cURL that is on the server, or something else like that. Going to move to wp's own request library and see if that helps, but it's a bit of a guess at the moment.

@8BrickDMG since you added the token directly in the db, have you since been able to cross-post to Medium?

**Comment by Chrisjgreenough** [comment] 2015-11-06 05:56
@majelbstoat   ![screen shot 2015-11-06 at 1 52 25 pm](https://cloud.githubusercontent.com/assets/15665512/10990403/affde5c8-848d-11e5-9ec2-db7902979908.png)
We are looking into our server to see if it's a server error on our end.

**Comment by Chrisjgreenough** [comment] 2015-11-06 07:26
@majelbstoat it was our cURL version. Thanks!

**Comment by majelbstoat** [comment] 2015-11-06 07:27
Awesome, thanks for double-checking. Hopefully the move to wp_remote_get() in the next version will catch and fallback to an alternative for others.

**Comment by majelbstoat** [comment] 2015-11-06 07:27
(What cURL version did you have? And what version worked?)

**Comment by majelbstoat** [comment] 2015-11-06 08:02
@wjmoner, @8BrickDMG, I just merged a patch to use WP's standard request libraries. If you're able, can you upgrade to this version, and let me know if it solves the problem?

If it doesn't, it's likely to be your curl config/version, as it was for Chris, but would be good to know if this actually solves the problem.

**Comment by wjmoner** [comment] 2015-11-06 15:00
@majelbstoat Thanks for all your help! The new plugin connected using my Medium token without trouble. Great work, thanks!

To answer your question, curl 7.35.0 (x86_64-pc-linux-gnu)

**Comment by Chrisjgreenough** [comment] 2015-11-07 11:07
@majelbstoat we used the latest edge version from apt-get.

**Comment by majelbstoat** [comment] 2015-11-08 22:51
Going to call this fixed. Thanks for debug help everyone.

**Closed by majelbstoat** 2015-11-08 22:51 UTC
